### ISSUE TITLE
How do I activate the zen mode (or any other mode)?

### ISSUE THREAD

**Issue by mairanteodoro** [n1k0laj/distraction-free#1]
Hi!

I'm trying to enter the zen mode but I cannot find the corresponding keystroke. The Github package says it can be activated with `ctrl-k ctrl-z `, but that doesn't work to me. If I use go to Setting (in Atom) and check the Keybindings there, I can see the Keystrokes as `space f z` (see link to screenshot)... what does that mean?

https://www.dropbox.com/s/xfoge1ld4p77e3d/Screenshot%202017-02-12%2011.39.09.png?dl=0

**Comment by nikolaiborisik** [comment]
Hi @mairanteodoro  
Looks like you use MacOs. I have added shortcuts for MacOs in the new version. You can update package.
**Shortcuts are** 
* cmd-k cmd-z - Toggle zen mode
* cmd-k cmd-f - Toggle more space for active panel mode
* cmd-k cmd-+ - Increase active panel size in the More space for active panel mode
* cmd-k cmd-0 - Decrease active panel size in the More space for active panel mode 

Or you can set what keys you want in the your **keymap.cson**

 ```
".platform-darwin":{
    "cmd-k cmd-z": "distraction-free:zen-toggle",
    "cmd-k cmd-f": "distraction-free:more-space-to-active-toggle",
    "cmd-k cmd-+": "distraction-free:more-space-to-active-increase",
    "cmd-k cmd--": "distraction-free:more-space-to-active-decrease"
  },
```

**Comment by mairanteodoro** [comment]
Thanks for adding the shortcuts for macOS @n1k0laj ! It's working now.
BTW, congrats for such nice project! ;)
